---
- hosts: pi
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml
      tags: ['always']

    - name: Include hook-pre-tasks.yml if it exists.
      include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - hook-pre-tasks.yml
          skip: true
      tags: ['always']

    - import_tasks: tasks/init.yml

  roles:
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.git
    - name: geerlingguy.nginx
      tags: ['nginx']
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Include hook-tasks.yml if it exists.
      include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - hook-tasks.yml
          skip: true

    - import_tasks: tasks/docker-compose-setup.yml

    - name: Copy nginx configuration into place.
      template:
        src: "templates/{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0644
      notify: restart nginx
      with_items:
        - src: proxy.conf.j2
          dest: /etc/nginx/conf.d/proxy.conf
        - src: drupal.conf.j2
          dest: /etc/nginx/sites-enabled/drupal.conf
      tags: ['nginx']
