---
- src: geerlingguy.composer
  version: 1.4.0
- src: geerlingguy.drush
  version: 1.1.2
- src: geerlingguy.firewall
  version: 1.0.9
- src: geerlingguy.git
  version: 1.1.1
- src: geerlingguy.mysql
  version: 2.2.1
- src: geerlingguy.nginx
  version: 1.9.2
- src: geerlingguy.php
  version: 2.0.3
- src: geerlingguy.php-mysql
  version: 1.2.0
- src: geerlingguy.security
  version: 1.2.0
