# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = 'local.drupalpi.test'
  config.vm.network :private_network, ip: '192.168.29.42'

  # VirtualBox configuration.
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ['modifyvm', :id, '--audio', 'none']
  end

  # SSH options.
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  # Vagrant box.
  config.vm.box = 'geerlingguy/debian9'

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../main.yml"
    ansible.inventory_path = "inventory"
    ansible.limit = "all"
    ansible.compatibility_mode = "2.0"
  end

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define 'drupal-pi' do |t|
  end

end
